stages:
  - build
  - test
  - deploy
  - deploy_artifact
  - kubernetes_manifest

variables:
  SONAR_URL: "http://10.0.0.13:9000"
  DOCKER_IMAGE: "raziels/ultimate-cicd:${CI_COMMIT_SHORT_SHA}"

build:
  stage: build
  tags:
    - "raziel-runner-pc"
  image: maven:3.8.4-openjdk-17-slim
  script:
    - echo "Building Maven package..."
    - mvn clean package
  artifacts:
    paths:
      - target/ultimate-cicd-1.0.jar

test:
  stage: test
  tags:
    - "raziel-runner-pc"
  image: maven:3.8.4-openjdk-17-slim
  script:
    - echo "Running SonarQube Analysis..."
    - mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL} -Dsonar.projectKey=com.raziel:ultimate-cicd -Dsonar.projectName="Ultimate CI/CD Project" -Dsonar.java.binaries=. -f pom.xml
  dependencies:
    - build

deploy:
  stage: deploy
  tags:
    - "raziel-runner-pc"
  script:
    - echo "Uploading application to Docker Hub..."
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  dependencies:
    - build

deploy_artifact:
  stage: deploy_artifact
  tags:
    - "raziel-runner-pc"
  script:
    - echo "Uploading to Nexus Artifact Repository..."
    - mvn deploy -Dmaven.test.skip=true -s settings.xml
  dependencies:
    - build

kubernetes_manifest:
  stage: kubernetes_manifest
  image: docker:20.10.12
  services:
    - docker:20.10.12-dind
  before_script:
    - apk add --no-cache openssh git
    - mkdir -p ~/.ssh  # Use user's home directory
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - git config --global user.email "razupx@gmail.com"
    - git config --global user.name "Raziel Sakira"
    - git clone git@gitlab.com:razielsa/manifests-projects.git /tmp/manifests-projects  # Clone into /tmp
    - cd /tmp/manifests-projects
    - sed -i "s/ultimate-cicd:.*/ultimate-cicd:${CI_COMMIT_SHORT_SHA}/g" ultimate-cicd-manifest/deployment.yml
    - git add spring-boot-app-manifests/deployment.yml
    - git commit -am "Update Image"
    - git push
  dependencies:
    - build